source 'https://rubygems.org'
ruby '~> 2.6.3'

group :jekyll_plugins do
    # gem 'github-pages'
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'jekyll-seo-tag'
    gem 'jekyll-sitemap'
end


# source 'https://rubygems.org'
# ruby '~> 2.6.3'
#
# group :jekyll_plugins do
#     # gem 'github-pages'
#     gem "nokogiri", ">= 1.6.7.rc"
#     gem 'jekyll', "~> 4.2.0"
#     gem 'jekyll-email-protect'
#     gem 'jekyll-paginate-v2'
#     gem 'jekyll-scholar'
#     gem 'jemoji'
#     gem 'unicode_utils'
#     gem 'jekyll-seo-tag'
#     gem 'jekyll-sitemap'
#     gem 'webrick'
#     gem 'kramdown-parser-gfm'
# end


# source 'https://rubygems.org'
#
# group :jekyll_plugins do
#     gem 'github-pages'
#     gem 'jekyll'
#     gem 'jekyll-email-protect'
#     gem 'jekyll-paginate-v2'
#     gem 'jekyll-scholar'
#     gem 'jemoji'
#     gem 'unicode_utils'
#     gem 'jekyll-seo-tag'
#     gem 'jekyll-sitemap'
#     gem 'kramdown-parser-gfm'
# end
